dependencies:
  - name: redis
    version: "1" #"^10.8.2"
    # repository: "https://charts.bitnami.com/bitnami"
    # condition: redis.enabled
  - name: postgresql
    version: "1" #"^8.10.14"
    # repository: "https://charts.bitnami.com/bitnami"
    # condition: postgresql.enabled